### ISSUE TITLE
Cameras with duplicate names but non-duplicate lens type cannot be created

### ISSUE THREAD

**Issue by amukher14** [childeqi/RTVE#16]
The user should be able to have two cameras with the same name as long the lens type is different (i.e. the user should be able to add a camera named “Canon: Wide” and another camera named “Canon: Tight”)

Currently if a camera named  “Canon: Wide” exists as you try to save “Canon: Tight" it will throw an error saying that the camera already exists.

**Comment by mschnur** [comment]
@dom-o, can the XML output handle having duplicate names?

**Comment by mschnur** [comment]
Btw, @amukher14, the title of the issue should be something that is a short summary of the issue, like a headline.  For this, something along the lines of "Cameras with duplicate names but non-duplicate lens type cannot be created"

**Comment by amukher14** [comment]
Okay that makes sense. Thanks for letting me know, I'll do that in the future.

**Comment by dom-o** [comment]
It can.

**Comment by mschnur** [comment]
Ok, in that case I can change the rules to allow duplicate names as long as the lens types are different. 
@dom-o, just out of curiosity, how does the XML identify each camera?  Do you assign them a number or something like that?
